### ISSUE TITLE
Check BasicTypes math operands

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#103]
Check the behavior of basic types (such as UBInt8) regarding math operations (addition, subtraction, etc).
For example:

```python3
a = UBInt8(1)
a - 1
1 - a
b = UBIntu(2)
a - b
b - a
```

**Comment by macartur** [comment]
To fix this we need to implement the method __radd__ and __rsub__.
I will implement this method and add __or__, __and__, __xor__ to be able bitwise operation.

**Comment by diraol** [comment]
@macartur the PR #190 is sufficient to close this issue?

**Comment by macartur** [comment]
Yes, I will change the last commit to use fix #103.

**Comment by diraol** [comment]
Don't worry about this issue/commit, just keep it in mind for the next time
=)​

**Comment by macartur** [comment]
Done.

**Comment by diraol** [comment]
@macartur this branch has already been merged into the develop branch, with the older commit. This commit won't be used anymore.
