### ISSUE TITLE
Represent IP address in 32 bits

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#112]
So far, the user is responsible to make the conversion. It would be better for the user to use regular IP address like 8.8.8.8 and to have it transparently converted to its 32-bit representation 134744072. Probably `basic_types.IPAddress`. For conversion details: http://www.aboutmyip.com/AboutMyXApp/IP2Integer.jsp.

**Comment by beraldoleal** [comment]
Please refer to issue #85 .
