### ISSUE TITLE
Generate binary packages for tests

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#122]
We need to generate the binary package for each type of openflow message so we can do pack and unpack tests.

The messages of `v0x01` are:
- **Asynchronous** messages:
  - [ ] error_msg.py
  - [ ] flow_removed.py
  - [ ] packet_in.py
  - [ ] port_status.py
- **Controller2Switch** messages
  - [ ] aggregate_stats_reply.py
  - [ ] aggregate_stats_request.py
  - [x] barrier_reply.py
  - [x] barrier_request.py
  - [ ] desc_stats.py
  - [x] features_reply.py
  - [x] features_request.py
  - [ ] flow_mod.py - flow_add
  - [x] flow_mod.py - flow_delete
  - [ ] flow_stats.py
  - [ ] flow_stats_request.py
  - [ ] get_config_reply.py
  - [ ] get_config_request.py
  - [ ] packet_out.py
  - [ ] port_mod.py
  - [ ] port_stats.py
  - [ ] port_stats_request.py
  - [ ] queue_get_config_reply.py
  - [ ] queue_get_config_request.py
  - [ ] queue_stats.py
  - [ ] queue_stats_request.py
  - [x] set_config.py
  - [ ] stats_reply.py
  - [ ] stats_request.py
  - [ ] table_stats.py
- **Symmetric** messages
  - [x] echo_reply.py
  - [x] echo_request.py
  - [x] hello.py
  - [ ] vendor_header.py

**Comment by cemsbr** [comment]
Some files of unchecked messages are available, but, as we don't know their content, they must be regenerated. Maybe we should also save a text file with their content.

**Comment by cemsbr** [comment]
This is blocking issue #8.

**Comment by erickvermot** [comment]
This should be easier with this:
[pyof_enhancement_proposal_01_draft](https://github.com/erickvermot/python-openflow/blob/pyof_ep_01/docs/blueprints/pyof-EP01-draft.rst)

**Comment by abaruchi** [comment]
Since @erickvermot proposal is under review, should we generate these messages with Wireshark (as before) or it will be on hold?

**Comment by beraldoleal** [comment]
@abaruchi on hold. Besides this is not for this milestone.

**Comment by cemsbr** [comment]
They can not be generated easily. Closed due to inactivity.
