### ISSUE TITLE
"Body", "Data", "Ports" and other attributes

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#13]
Some classes have attributes that represents a list of objects*.

Implement a new basic type that represents a list that guarantee the type of the list items and also work as a `descriptor`.

This behaviour can be found on:
  - **properties**:
    - [x] `struct ofp_packet_queue`
  - **ports**:
    - [x] `struct ofp_switch_features` (`features_reply`)
  - **actions**:
    - [x] `struct ofp_flow_mod`
    - [x] `struct ofp_flow_stats`
    - [x] `struct ofp_packet_out`
  - **queues**:
    - [x] `struct ofp_queue_get_config_reply`
  - **body**:
    - [x] `struct ofp_stats_request`
    - [x] `struct ofp_stats_reply`
  - **data**:
    - [ ] `struct ofp_packet_out`
    - [ ] `struct ofp_packet_in`
    - [x] `struct ofp_error_msg`

* These attributes are represented as an array of pointers to structs on the spec,

**Comment by diraol** [comment]
We have created a "SpecialList" class, inherited from "list" and that act as a "descriptor". It also checks the "type" of the items that are trying to be inserted on the list.

Now we should create one child class to each case when this behavior is needed.

**Comment by beraldoleal** [comment]
To make it easy, for now, we should create a GenericList where can accept any element of any type. During pack() we should create an exception when for instance body_type is different of all elements of this list.

**Comment by diraol** [comment]
Waiting for discussion related to the "data" attribute of packet_out and packet_in messages. Except for that, everything is done.
