### ISSUE TITLE
Echo Request/Reply structure (data value)

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#136]
Reading the OF v0x01 I've noticed that the Echo Request/Reply _can_ have an arbitrary `data` field, but it does not exists on the `struct`.

> EchoReq in this version has a header and optionally a variable length field, data, containing arbitrary information, such as latency (timestamp), bandwidth, liveness, etc. EchoRes shares the same structure with EchoReq. The EchoRes data is an exact copy of the data present from the corresponding EchoReq.

How to deal with it? If it was just binary data it would be easy, but "random" fields it is more complicated.
Or can we implement, in our library, some fields (timestamp for example)?

**Comment by beraldoleal** [comment]
I think that this can be implemented by our side to check latency for instance. We insert a timestamp value on Echo Request and probably the switch will reply with the same data, right ?

**Comment by diraol** [comment]
Yes, if the sent echo request packet has the data field the switch may send it back on the echo reply, with the same data field (same binary data).
But, for now, we don't have the "data" field on the EchoRequest/Reply classes, as it can be seen here:
https://github.com/kytos/python-openflow/blob/develop/pyof/v0x01/symmetric/echo_request.py
https://github.com/kytos/python-openflow/blob/develop/pyof/v0x01/symmetric/echo_reply.py

So, what I'm proposing is to add a "data = BinaryData()" field on our class, after the header of the message.

**Comment by beraldoleal** [comment]
Yes, go ahead, @diraol . I will open a new issue to implement the latency, latter.
