### ISSUE TITLE
Generate Technical Documentation

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#14]
For now we will use pydoc and the host on our virtualmachine to share the documentation of the project.

For this, we need to:
  - [ ] Specify how the "pydoc process" will happen
  - [ ] **create a git hook** to update this doc after each push on master branch

**Comment by diraol** [comment]
To correctly format python docstrings to generate the documentation with sphinx, look at:

https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example

We need to choose a model to our docstrings that feels good both on source code and web documentation.

**Comment by beraldoleal** [comment]
Here is a simple example. For more information please visit: 

https://pythonhosted.org/an_example_pypi_project/sphinx.html

`        """Return all tags whose names contain a given string.

        By default only free tags (tags which do not belong to any vocabulary)
        are returned. If the optional argument ``vocab_id_or_name`` is given
        then only tags from that vocabulary are returned.

        .. note:: test of a note

        :param search_term: the string to search for in the tag names
        :type search_term: string
        :param vocab_id_or_name: the id or name of the vocabulary to look in
            (optional, default: None)
        :type vocab_id_or_name: string

        :returns: a list of tags that match the search term
        :rtype: list of ckan.model.tag.Tag objects

        These are written in doctest format, and should illustrate how to use
        the function.

                >>> a=[1,2,3]
                >>> print [x + 3 for x in a]
                [4, 5, 6]
        """
`

**Comment by beraldoleal** [comment]
Automatic docs on sphinx will be improved with a new layout. But for now we have a "ok" example from foundation. Please lets follow this style.

http://docs.kytos.io/python-openflow/pyof.v0x01.foundation.html
