### ISSUE TITLE
[v0x02] Implement v0x02 differences

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#146]
- [x] New Header version (redefine constant)
- [x] enum ofp_type
  - Rename OFPT_VENDOR to OFPT_EXPERIMENTER
  - Add OFPT_TABLE_MOD after OFPT_PORT_MOD
- [x] struct ofp_phy_port
  - Rename to ofp_port
  - Rename uint16_t port_no to uint32_t
  - Add 2 paddings
  - Add 2 speed fields
  - From 48 to 64 bytes
- [x] enum ofp_port_config
  - Remove OFPPC_NO_STP, OFPPC_NO_RECV_STP and OFPPC_NO_FLOOD
- [x] enum ofp_port_state
- [x] enum ofp_port
  - Rename to ofp_port_no
  - New values
  - Rename OFPP_NONE to OFPP_ANY
- [x] enum ofp_port_features: new values
- [x] New enum ofp_match_type
- [x] struct ofp_match
  - New fields
  - Size is OFPMT_STANDARD_LENGTH = 88
- [x] enum ofp_flow_wildcards: different fields
- [ ] New enum ofp_vlan_id
- [ ] New enum ofp_instruction_type
- [ ] New struct ofp_instruction_goto_table
- [ ] New struct ofp_instruction_write_metadata
- [ ] New struct ofp_instruction_actions
- [ ] enum ofp_action_type: different values
- [ ] struct ofp_action_output:
  - Add fields
  - New size
- [ ] New struct ofp_action_group
- [ ] struct ofp_action_enqueue:
  - Rename to ofp_action_set_queue
  - Different field size, no padding
- [ ] New struct ofp_action_mpls_tc
- [ ] New struct ofp_action_mpls_ttl
- [ ] New struct ofp_action_nw_ecn
- [ ] New struct ofp_action_nw_ttl
- [ ] New struct ofp_action_push
- [ ] struct ofp_action_vendor_header
  - Rename to ofp_action_experimenter_header
  - Rename field
- [x] struct ofp_switch_features: change 2 last fields
- [x] enum ofp_capabilities: different fields
- [ ] enum ofp_config_flags: new field
- [ ] New struct ofp_table_mod
- [ ] New enum ofp_table_config
- [ ] struct ofp_flow_mod: new fields
- [ ] enum ofp_flow_mod_flags: remove last field
- [ ] New struct ofp_group_mod
- [ ] New enum ofp_group_mod_command
- [ ] New enum ofp_group_type
- [ ] New struct ofp_bucket
- [ ] struct ofp_port_mod: new types and fields
- [ ] struct ofp_queue_get_config_request: different sizes
- [ ] struct ofp_queue_get_config_reply: different sizes
- [ ] struct ofp_stats_request: add padding
- [ ] struct ofp_stats_reply: add padding
- [ ] enum ofp_stats_types
  - New and renamed fields
  - Different value
- [ ] struct ofp_flow_stats_request: new fields
- [ ] struct ofp_flow_stats: new fields 
- [ ] struct ofp_aggregate_stats_request: new fields
- [ ] struct ofp_table_stats: different fields 
- [ ] struct ofp_port_stats_request: new port size
- [ ] struct ofp_port_stats: new port size
- [ ] struct ofp_queue_stats_request: new port size
- [ ] struct ofp_queue_stats: new port size
- [ ] New struct ofp_group_stats
- [ ] New struct ofp_bucket_counter
- [ ] New struct ofp_group_desc_stats
- [ ] struct ofp_packet_out: new port size
- [ ] struct ofp_packet_in: different fields
- [ ] struct ofp_flow_removed: new fields
- [x] enum ofp_flow_removed_reason: new value (last one)
- [x] struct ofp_port_status: different last-field type (and new size)
- [x] enum ofp_error_type: new and changed values
- [x] enum ofp_bad_request_code: new values
- [x] enum ofp_bad_action_code: new values
- [x] New enum ofp_bad_instruction_code
- [x] New enum ofp_bad_match_code
- [x] enum ofp_flow_mod_failed_code: different fields
- [x] New enum ofp_group_mod_failed_code
- [x] enum ofp_port_mod_failed_code: new values
- [x] New enum ofp_table_mod_failed_code
- [x] struct ofp_vendor_header: rename to struct ofp_experimenter_header

References:
- [OpenFlow Switch Specification 1.0.0 ](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.0.0.pdf)
- [OpenFlow Switch Specification 1.1.0 ](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.1.0.pdf)

**Comment by diraol** [comment]
@cemsbr the 'version' on the ``base.py`` file should be **0x02** or **"0x02"** (with quotes)?

**Comment by cemsbr** [comment]
@diraol , version's type is uint8_t (C), so we should keep it as an int (Python) as it was in v0x01.

**Comment by cemsbr** [comment]
In v0x02, we should import other modules from v0x02, no matter if the other modules were changed or not. If we import unchanged modules from v0x01 instead, it will be difficult to know from which version we should import in v0x03, v0x04, etc...

Of course, if we have no changes in a module, we just create a file importing it from v0x01. This was done in #147, for every module.

**Comment by cemsbr** [comment]
@diraol , I'm not sure if we should redefine MAXID in Header or import it from v0x01.

**Comment by diraol** [comment]
@cemsbr agreed about MAXID, done it on 41bf1b4 =)
