### ISSUE TITLE
[v0x02] Start v0x02 by importing v0x01

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#147]
In pyof/v0x02, replicate module structure and import its previous version (v0x01). As discussed with @diraol, the imports should be explicit.

**Comment by diraol** [comment]
Folks, you allow me a suggestion, I think that it is better for everyone to work on one branch for each module (asynchronous, controller2switch, etc).... It would make easier to merge and also may allow rebases without bigger problems.

**Comment by beraldoleal** [comment]
How #146 is related to this ? They are complete different issues ? We can close one of them because is duplicate ?

**Comment by cemsbr** [comment]
This issue is done in a branch, but its approach for upgrading v0x02 will be changed. This issue is only about creating files and its import lines. However, during v0x04, we decided that it is better to copy the whole files and then update them. Thus, I'm closing this one and we should keep #146 open.
