### ISSUE TITLE
[v0x02] - FlowMod related questions

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#156]
Here we have some questions about `controller2switch.flow_mod.FlowMod` class attributes:
- Does `out_group` have any kind of constrain (`enum_ref`)?
- `instructions` is a `ListOfInstructions`, but what is a `ListOfInstructions`? Where do we define it?

**Comment by beraldoleal** [comment]
@diraol still valid ? Can you describe better, please ?

**Comment by diraol** [comment]
@beraldoleal this issue is for v0x02, that we haven't implemented. I think we can close this issue and, if we go back to v0x02 and this still an issue, then we can reopen this issue.
