### ISSUE TITLE
Implement OF v0x04 (1.3.0)

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#158]
For now, while we do not fix #157 , we will implement v0x04 (1.3.0) from the ground, by copying the v0x01 files and rewriting it.

*The bellow list still need to be reviewed in comparison with the spec.*

**Comment by diraol** [comment]
- **Asynchronous** messages:
  - [ ] error_msg.py
  - [ ] flow_removed.py
  - [ ] packet_in.py
  - [ ] port_status.py

**Comment by diraol** [comment]
- **Common** messages:
  - [ ] action.py
  - [ ] flow_match.py
  - [ ] header.py
  - [ ] phy_port.py
  - [ ] queue.py

**Comment by diraol** [comment]
- **Controller2Switch** Messages
  - [ ] aggregate_stats_reply.py
  - [ ] aggregate_stats_request.py
  - [ ] barrier_reply.py
  - [ ] barrier_request.py
  - [ ] common.py
  - [ ] desc_stats.py
  - [ ] features_reply.py
  - [ ] features_request.py
  - [ ] flow_mod.py - flow_delete
  - [ ] flow_mod.py - flow_add
  - [ ] flow_stats.py
  - [ ] flow_stats_request.py
  - [ ] get_config_reply.py
  - [ ] get_config_request.py
  - [ ] packet_out.py
  - [ ] port_mod.py
  - [ ] port_stats.py
  - [ ] port_stats_request.py
  - [ ] queue_get_config_reply.py
  - [ ] queue_get_config_request.py
  - [ ] queue_stats.py
  - [ ] queue_stats_request.py
  - [ ] set_config.py
  - [ ] stats_reply.py
  - [ ] stats_request.py
  - [ ] table_stats.py

**Comment by diraol** [comment]
- **Foundation**
  - [ ]  base.py
  - [ ]  basic_types.py

**Comment by diraol** [comment]
- **Symmetric** messages
  - [ ] echo_reply.py
  - [ ] echo_request.py
  - [ ] hello.py
  - [ ] vendor_header.py

**Comment by cemsbr** [comment]
Vou começar com o _Controller2Switch_.

**Comment by diraol** [comment]
I've done the common/header.py and now I'm working on the symmetric messages.

**Comment by diraol** [comment]
Symmetric finished. Going to common. If any of you guys need to change a file on that module, just let me know. =)

**Comment by abaruchi** [comment]
Im doing the async messages.

**Comment by diraol** [comment]
Symmetric and Asynchronous modules done and reviews (for lint errors).

**Comment by abaruchi** [comment]
`GET_CONFIG_REPLY` and `GET_CONFIG_REQUEST` messages type do not change in v0x04.

**Comment by abaruchi** [comment]
`set_config.py` remains the same for v0x04, no changes required. Only enum flags must be updated (was already fixed).
