### ISSUE TITLE
Create a validate() method

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#16]
We need to create a method validate() for all `basic_types` and structs (classes) to validate the messages and "structs" (classes) instances.
This validate() method should generate an exception when it fails.
  - [x] create the validate() method:
    - [x] validate attributes types
    - [ ] validate overflow behaviour
    - [ ] message size (?)
    - [ ] other specific validations defined on the specification (such as enum beloging, range validation, etc)
  - [ ] create the specific exceptions for the validation failure cases (to be defined)

**Comment by abaruchi** [comment]
Also, we should create a way to validade the values used to instantiate basic types classes (probably in UB* Classes, defined in `basic_types.py`). Right now these classes accept any kind of values (including characters and text). Refer to example below to more clarification:

````
In[10]: b = basic_types.UBInt8("arturbaruchi")
In[11]: b
Out[11]: UBInt8(arturbaruchi)
```
