### ISSUE TITLE
[v0x04] Helps on OF Spec understanding

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#164]
This issue will be focused on the understanding of OF Documentation (version `0x04`\- `1.3.0`).
For now, all doubts will be concentrated here, but we may split this issue into other issues for better organization purposes.

The first topic I'll address here is related to the `field` field of `ofp_action_field` struct (Page 52(51)).

It seems to be a UBInt8 array of size 4, and its content may be a "OXM TLV". But there it is not clear what is a OXM TLV. There is no structs on the spec for that, despite table 9 on page 41.

So, should we implement Table 9 as a struct and then use it on the `field` attribute of `ActionField`?

Other problem with that struct (`ofp_action_field`) is the comment right before `field`:

```
/* Followed by:
*     - Exactly oxm_len bytes containing a single OXM TLV, then
*     - Exactly ((oxm_len + 4) + 7)/8*8 - (oxm_len + 4) (between 0 and 7)
*       bytes of all-zero bytes
*/
```

So, this struct has a variable length?

@cemsbr if you can, please help improving this issue description.

**Comment by cemsbr** [comment]
Let's look at it more carefully later. Maybe there is more info in 1.3.x | x > 0. A TODO I removed from the code:
- [ ] Better comments in ActionSetField for field 1 to 4.

**Comment by diraol** [comment]
Another one that I didn't understood how to implement correctly is the ``AsyncConfig`` class.

```C++
/* Asynchronous message configuration. */
struct ofp_async_config {
    struct ofp_header header;      /* OFPT_GET_ASYNC_REPLY or OFPT_SET_ASYNC. */
    uint32_t packet_in_mask[2];    /* Bitmasks of OFPR_* values. */
    uint32_t port_status_mask[2];  /* Bitmasks of OFPPR_* values. */
    uint32_t flow_removed_mask[2]; /* Bitmasks of OFPRR_* values. */
};
OFP_ASSERT(sizeof(struct ofp_async_config) == 32);
```

But ``OFPR_*`` are defined on the ``PacketInReason`` *Enum*, and it is not a ``BitMask``:

```C++
enum ofp_packet_in_reason {
    OFPR_NO_MATCH = 0,
    OFPR_ACTION = 1,
    OFPR_INVALID_TTL = 2,
};
```

So, I thought about adding two fields for each array, like this:

```Python
class AsyncConfig(GenericMessage):
    #: message_type: Type.OFPT_GET_ASYNC_REPLY or Type.OFPT_SET_ASYNC
    header = Header();
    #: Bitmasks of OFPR_* values.
    packet_in_mask1 = UBInt32(enum_ref=PacketInReason)
    packet_in_mask2 = UBInt32(enum_ref=PacketInReason)
    #: Bitmasks of OFPPR_* values.
    port_status_mask1 = UBInt32(enum_ref=PortReason)
    port_status_mask2 = UBInt32(enum_ref=PortReason)
    #: Bitmasks of OFPRR_* values.
    flow_removed_mask1 = UBInt32(enum_ref=FlowRemovedReason)
    flow_removed_mask2 = UBInt32(enum_ref=FlowRemovedReason)
```

What do you think?
  - [ ] AsyncConfig implementation

**Comment by beraldoleal** [comment]
@diraol multiple questions on the same issue is not a good idea. Let's split this, please.

We have already 1.3.5, this is still valid ?

**Comment by diraol** [comment]
As I do not remember this clearly, and the team has worked a lot on `v0x04`, I'll close this issue. =)
