### ISSUE TITLE
[v0x04] Review action

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#165]
_ActionType_ was not updated and there were several linter issues. We should review this file to making sure nothing is missing.

**Comment by cemsbr** [comment]
About _ActionType_ specifically, I found 2 definitions (search for _enum ofp_action_type_ in spec). So I merged them.

**Comment by renanrodrigo** [comment]
@cemsbr , I Opened issue #296 before seeing this, sorry.
The ofp_action_type enum with values between 1 and 9 is the one used in older versions of OpenFlow. Those were substituted in 1.3.5 and deprecated. PR #300 removes them.

**Comment by beraldoleal** [comment]
PR #300 was merged. Can we close this ? @renanrodrigo @cemsbr ?

**Comment by renanrodrigo** [comment]
I think so. The class has the correct spec fields now.

**Comment by beraldoleal** [comment]
@cemsbr I 'm closing this, if you think that should be open, please reopen.
