### ISSUE TITLE
[v0x04] Validations

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#166]
I'm documenting here classes that have some possible validations that need to be implemented with the 'validate' or 'is_valid' methods.
- **asynchronous**
  - [ ] PacketIn - Possible validation on the padding and "data" attribute to fit 32-bit alignment.

**Comment by beraldoleal** [comment]
Is  this a duplicate issue for #96 ?

**Comment by beraldoleal** [comment]
@diraol ?

**Comment by diraol** [comment]
Yes!
Closing it! ;)
