### ISSUE TITLE
Change default init values of Attributes

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#173]
In some cases the user are not interested in filling out all attributes from a Class, such as the ``Match`` class (``pyof.v0x01.common.flow_match.Match``).

Considering that, we need to provide, on the ``__init__`` method, default values for the attributes that the user may ignore while using our lib.

**Comment by beraldoleal** [comment]
This is fixed, right ?

**Comment by diraol** [comment]
Regardubg the FlowMatch class yest, it is. [May be we would let this issue open and rewrite it to focus on default values of all attributes from pyof v0x01 classes?

**Comment by beraldoleal** [comment]
Maybe if it will be open, it will forever . Lets close for now.
