### ISSUE TITLE
Match "Mask" (Wildcard) autofill

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#180]
On version ``v0x01``, the ***wildcard*** field of ``Match`` class should be auto calculated/populated.

So we need a method on the ``Match`` class that will calculate the appropriated ***wildcard*** considering the attributes of the instance.

The description of the **wildcard** field on the spec is not clear, but it can be found at the item **5.3.2**.

Moreover, there is also the image below that can help understand the field and also this blog post: http://danny270degree.blogspot.com.br/2012/06/openflow-wildcard-explanation.html

![openflow-match-mask](https://cloud.githubusercontent.com/assets/192702/18682267/f1dbf5ca-7f41-11e6-909a-7b2c48149e15.png)

**Comment by macartur** [comment]
I have a question, in the class Match have a nw_src "IP source address", but this is represented by a int. However I need a ip address like "255.255.255.0/24". How can I get this ?

**Comment by diraol** [comment]
@macartur, for now this field is just a 'integer' field (UBInt). At some point we will create a "IPAddress" basic_type to use over there.

I think that the link below will help you understand how to do this conversion:
http://www.aboutmyip.com/AboutMyXApp/IP2Integer.jsp

Take a look at that and let me know if you still have any doubts ok?

**Comment by macartur** [comment]
Yes, I need only the subnet mask , like /24 or /16 to represent a  CIDR notation.

**Comment by macartur** [comment]
@diraol I made a commit adding a Autofill wildcards and IPAddress.

**Comment by diraol** [comment]
@macartur where did you made this commit? which branch?

**Comment by macartur** [comment]
Branch: issue-#180-v0x01

**Comment by diraol** [comment]
@macartur Thanks!

Please, do the PullRequest to the ``develop`` branch so we can review the commits =)

**Comment by diraol** [comment]
Hum... I will do the PR now because I've already thought on some comments and I don't want to forget them. rs
