### ISSUE TITLE
Implement latency on echo request/echo reply

### ISSUE THREAD

**Issue by beraldoleal** [kytos/python-openflow#189]
From spec:

> EchoReq in this version has a header and optionally a variable length field, data, containing arbitrary information, such as latency (timestamp), bandwidth, liveness, etc. EchoRes shares the same structure with EchoReq. The EchoRes data is an exact copy of the data present from the corresponding EchoReq.
#136 for more details.

**Comment by beraldoleal** [comment]
This logic should not be implemented on python-openflow, but on kytos-napps repository.

**Comment by erickvermot** [comment]
moved to [kytos-napps #190](https://github.com/kytos/kytos-napps/issues/190)
