### ISSUE TITLE
Verify OF 1.0.0 erratas (1.0.1 and 1.0.2)

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#2]
Check the implemented code with the 1.0.0 erratas:
  - [x] [1.0.1](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.0.1.pdf)
  - [x] [1.0.2](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.0.2.pdf)

**Comment by abaruchi** [comment]
Most of corrections are about switch behaviour (i.e.: how to handle malformed packets, Controller connection failure behaviour, openflow default port, and so on).

Corrections regarding Errata 1.0.1 and 1.0.2:
* Updated docstring about physical port 0 in phy_port.py file;
* Updated docstring about Virtual Ports restrictions in packet_out in file packet_out.py;
