### ISSUE TITLE
Fix "more than one target found for cross-reference"

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#211]
This causes lots of warnings during doc compilation. We must remove pyof version ambiguity in references. E.g.: `pyof.v0x01.common.header.Header` instead of `common.header.Header`. A relative reference would be better so the docstring can be reused in other pyof versions.

**Comment by beraldoleal** [comment]
How to reproduce this error ? Where you see this ?

**Comment by cemsbr** [comment]
The warnings ca be seen when running ``make -C docs/``.

**Comment by macartur** [comment]
Today the sphinx is broken. I will wait for next release '1.6.2' with the fix 'https://github.com/sphinx-doc/sphinx/issues/3772'.
