### ISSUE TITLE
network_types TODOs

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#215]
In pyof/foundation/network_types.py:
- [x] GenericTLV.get_size: 3-letter comment followed by "???!!?!?!?"

**Comment by diraol** [comment]
@cemsbr is this issue still valid?!

**Comment by cemsbr** [comment]
@beraldoleal , what do you mean by *duplicated* in the first TODO item added by https://github.com/kytos/python-openflow/commit/e31a687b0c317d2387cd1c59143f1cce0e1a98ff?

**Comment by beraldoleal** [comment]
@cemsbr I have no idea. hahah, Removing
