### ISSUE TITLE
Review *type* attributes

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#217]
By using `type` as a variable, we override the Python built-in `type`, which is dangerous, and generate linter warnings. However, it is possible to use `type` as an attribute. Right now, some classes use prefixes like ``Header.message_type`` and others use simply `type` as attribute and a different name for parameter, e.g.:
```python
class GenericTLV:
    def __init__(self, tlv_type=127, value=None):
        self.type = tlv_type
```
We should set a convention here and I see 2 possibilities:
1. Do like `GenericTLV`;
1. Always use a prefix.

The first one has the advantage of always being able to use `obj.type`, but we would have to know the prefix to pass the value in the constructor anyway. Therefore, the second option seems to be the simplest rule.

**Comment by renanrodrigo** [comment]
I think the prefix is always being applied to type elements on the code (except in `/foundation/basic_types.py`, where GenericTLV and Ethernet are defined). Will these two be changed to match the rest of the code?

**Comment by beraldoleal** [comment]
Just to add some fire to this discussion:

From PEP8:

> If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore rather than use an abbreviation or spelling corruption. Thus class_ is better than clss. (Perhaps better is to avoid such clashes by using a synonym.)

**Comment by diraol** [comment]
I think that worth add this too (from the PEP8 second 'chapter'):
```
A Foolish Consistency is the Hobgoblin of Little Minds
One of Guido's key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As PEP 20 says, "Readability counts".

A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

However, know when to be inconsistent -- sometimes style guide recommendations just aren't applicable. When in doubt, use your best judgment. Look at other examples and decide what looks best. And don't hesitate to ask!

In particular: do not break backwards compatibility just to comply with this PEP!

Some other good reasons to ignore a particular guideline:

When applying the guideline would make the code less readable, even for someone who is used to reading code that follows this PEP.
To be consistent with surrounding code that also breaks it (maybe for historic reasons) -- although this is also an opportunity to clean up someone else's mess (in true XP style).
Because the code in question predates the introduction of the guideline and there is no other reason to be modifying that code.
When the code needs to remain compatible with older versions of Python that don't support the feature recommended by the style guide.```

**Comment by renanrodrigo** [comment]
From my POV, we have two viable options then:
1. Rename the the remaining two `type` attributes with a prefix (as stated in the text about consistency), or
2. Stick hard to the recommendation and rename all of the `type`s as `type_`.

I vote for 1. 
Main reason is: none of them are 100% compliant with the spec, but having a prefix sounds better in the general usability of the lib, IMHO.

**Comment by diraol** [comment]
Agree, I also vote for option *1* =)

**Comment by beraldoleal** [comment]
Ok, we can go for 1. But I'm not 100% sure that this is the best option. Let's move one and make it consistent, then on the future we can come back to this again.

**Comment by cemsbr** [comment]
After @renanrodrigo's note about spec compatibility, I believe that the only way to have 100% spec compatibility and no problem with reserved words is using the option 1 of the first post. Should we open an issue to verify that we are always using *type* as attribute when the spec says so (with a prefixed parameter)?

**Comment by beraldoleal** [comment]
@cemsbr. Wait! I said option 1 for the @renanrodrigo post not the first post.

**Comment by renanrodrigo** [comment]
@cemsbr I checked it. The classes `GenericTLV` and `Ethernet` are using the first option from the first post. All the other classes are using the prefix.

I can take care of these situations, just need to know what we'll have as the default.

**Comment by beraldoleal** [comment]
@renanrodrigo just to confirm. The option that you are going to implement is with prefix.

**Comment by cemsbr** [comment]
I understood that @beraldoleal was talking about the first option of @renanrodrigo post and that is a quick solution for consistency. However, I also think that, later (more time consuming), we'd better not use, i.e. ``msg_type`` as attribute if spec says ``type``. In such case, ``msg_type`` would be used only as a constructor parameter to avoid name clash with Python's ``type``. Thus, if the user reads ``type`` in the spec, he can use ``object.type``.

**Comment by renanrodrigo** [comment]
@cemsbr Seems like a more elegant solution. But as you said, the developer will need to know the prefix to pass the value to the constructor. Isn't creating an instance using `class = Class(xy_type='z')` and then accessing this attribute as `class.type` a kind of inconsistency?

**Comment by beraldoleal** [comment]
@cemsbr. I don't like this option. It creates inconsistency.

**Comment by cemsbr** [comment]
We either have to be inconsistent with parameter vs attribute or with the spec. A third option is to use ``type`` as both parameter and attribute, be very careful when using Python's ``type`` inside the constructor and ignore such linter warning.

**Comment by beraldoleal** [comment]
@cemsbr prefix_<reserved_word> is the best option for now.
