### ISSUE TITLE
Error while migrating to python 3.6

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#238]
While testing the full project on python 3.6 (running kyco against a mininet instance with 3 hosts and 3 switches, no loop version), the error below were throughed on the kytos console:

> Exception in thread Thread-198:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/diraol/devel/kyco/kyco/utils.py", line 70, in threaded_handler
>     handler(*args)
>   File "/home/diraol/.virtualenvs/python-openflow/var/lib/kytos/napps/kytos/of_lldp/main.py", line 78, in update_links
>     lldp.unpack(ethernet.data.value)
>   File "/home/diraol/devel/python-openflow/pyof/foundation/base.py", line 431, in unpack
>     size = self._unpack_attribute(name, value, buff, begin)
>   File "/home/diraol/devel/python-openflow/pyof/foundation/base.py", line 441, in _unpack_attribute
>     attribute.unpack(buff, begin)
>   File "/home/diraol/devel/python-openflow/pyof/foundation/network_types.py", line 132, in unpack
>     self.value = BinaryData(buffer[begin:end])
> AttributeError: can't set attribute

@cemsbr, please, address this error as soon as possible so we can have the project working on Python 3.6 =)

**Comment by cemsbr** [comment]
Note: this would happen in any Python version.
