### ISSUE TITLE
Enable this repo in coveralls

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#246]
An administrator should login in coveralls and click in this repository name to enable the tracking of test coverage.

Note: the coverage will be available after the next commit in the develop branch. Preview: https://coveralls.io/github/cemsbr/python-openflow (will be removed after closing this issue).

**Comment by cemsbr** [comment]
Please, enable kyco also.

**Comment by cemsbr** [comment]
It seems it is not enabled.

**Comment by diraol** [comment]
I think that this issue can be closed now that we are using scrutinizer, right @cemsbr ?

**Comment by cemsbr** [comment]
Deprecated in favor of Scrutinizer.
