### ISSUE TITLE
OF 1.3 Compliance: additional ENUM attribute

### ISSUE THREAD

**Issue by abaruchi** [kytos/python-openflow#255]
File: `v0x04/common/action.py`

`class ActionType(Enum):`

There is a enum attribute that is not present in 1.3 spec with duplicate value. Remove `OFPAT_EXPERIMENTER` and keep only `OFPAT_VENDOR`

```
    OFPAT_EXPERIMENTER = 0xffff
    OFPAT_VENDOR = 0xffff
```

**Comment by renanrodrigo** [comment]
OFPAT_EXPERIMENTER is the filed defined in the spec. Removing OFPAT_VENDOR instead.
