### ISSUE TITLE
OF 1.3 Compliance: Wrong pad attribute size

### ISSUE THREAD

**Issue by abaruchi** [kytos/python-openflow#265]
File: `v0x04/controller2switch/common.py`

`class PortStatsRequest(GenericStruct):`
In source code the pad attribute size is set to 6, but in 1.3 Spec it is 4.

Espec 1.3: `pad[4]`
Source Code: `pad = Pad(6)`

**Comment by renanrodrigo** [comment]
In the same class in the source code, `port_no = UBInt16()`, but it has 32 bits in the spec (and in other locations on the code). Correcting that also.
