### ISSUE TITLE
Add prerequisites and dependencies to Documentation

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#297]
There's no reference to pre-requisites or installing order in the docs.

**Comment by erickvermot** [comment]
Checking if I understood correctly:
in docs/toc/indrocution.rst there should be a reference to the requirements and requirements-dev content. Is that it?
Should it "include" the contents from the files, or just include manually some text?
There are no requirements for use. Does it really need a reference?

**Comment by renanrodrigo** [comment]
I think @beraldoleal and @cemsbr changed the `setup.py` to automatically install the requirements. If so, the issue can be closed.
* Is python3.6 installed with the requirements? If no, then need to add a line about installing python3.6 I think.

**Comment by beraldoleal** [comment]
Ok, the ideia here is:

We don't need to have a documentation to explain in details how to install the requirements. As @renanrodrigo said, we changed the setup.py to install the python requirements automatically.

But , regards python3.6 yes, this is a strong requirement and we should at least have a mention for this after the first paragraph of Install section. This should also be applied to kytos and kytos-utils.

**Comment by erickvermot** [comment]
As I see it, maybe setup.py should check if the correrct python version (>=3.5 ?) is beeing used. right?

**Comment by renanrodrigo** [comment]
More than that, some Ubuntu versions don't have python3.6 in the standard repository. The installation instructions are in the tutorial page.

**Comment by diraol** [comment]
Lot's of distros does not offers python3.6 in its standards repositories.
But, as beraldo said, it is good to disclose that python3.6 is a
requirement from our project, but we do not need to cover its installation.
​
