### ISSUE TITLE
Ensure the elements type of a list 

### ISSUE THREAD

**Issue by abaruchi** [kytos/python-openflow#3]
Implement a way to ensure that all elements of an empty list has a specific type. 

For example, in flow_stats.py (defined in [page 32](http://archive.openflow.org/documents/openflow-spec-v1.0.0.pdf#page=32) of OF 1.0.0 specs) ```actions``` will be an empty list and all elements must be instances of the class ofp_action_header.

```
struct ofp_action_header actions[0]; /* Actions. */
```

**Comment by diraol** [comment]
This is going to be resolved on #13
