### ISSUE TITLE
1.3.5 Compliance - Hello messages with optional elements

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#303]
Must implement Hello messages class (0x04/symmetric/hello) according to 1.3.5.
Since 1.3.1, hello messages should accept optional ofp_hello_elem elements like the VERSIONBITMAP for example, to avoid problems with version negotiation, or provide space for possible future extensions of the hello message.

**Comment by beraldoleal** [comment]
@renanrodrigo did you started this ? How long to finish ?
