### ISSUE TITLE
1.3.5 Compliance - implement symmetric/experimenter arbitrary data field

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#304]
Implement arbitrary data field.
OF 1.3.5: symmetric/experimenter - should be able to receive arbitrary data (BinaryData) as parameter and carry it, as in echo messages.

**Comment by renanrodrigo** [comment]
The spec (in 7.5.4) defines `struct ofp_experimenter_header`, and we have the associated class in the code. Does it make sense to add a field in a header struct? IMHO, the experimenter who is writing/testing a new symmetric message would use the Header class and add fields himself to the message, à la carte.

**Comment by beraldoleal** [comment]
I think that our lib must provide a BinaryData field anyway. So the experimenter uses this field.
We just need to make sure that `length` attribute is being filled right, when this field is used. According to @diraol this "automatic len" is working for this case. But is a good idea to check if we have tests for this.

**Comment by cemsbr** [comment]
The spec says in the last line: ``/* Experimenter-defined arbitrary additional data. */``. I think we should add a ``data`` field in case a vendor wants to add his own data.
