### ISSUE TITLE
Multipart request/reply bodies code need refactoring.

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#306]
As it is now, all the Multipart request/reply bodies are in `/controller2switch/common.py`. As they are not common structures, they should be located at `multipart_request.py` or `multipart_reply.py` according to the specific message they belong to. Besides context correction, this reduces the amount of classes in `common.py`.

**Comment by beraldoleal** [comment]
@diraol can you confirm, please ?

**Comment by diraol** [comment]
@beraldoleal I've talked to @renanrodrigo on the IRC about this issue last week.

We will probably need to create some new classes (for each specific message, such as we have done on `Action*` classes on `v0x01`), and relocate some others.

Considering the problem of `common.py` getting too long, we have also discussed the possibility of converting it into a submodule (directory) and creating separate file for the classes we are putting into it, exporting them to the `__init__.py` file of this new submodule (to avoid extremely long imports). But this last item is not going to be addressed for now.

**Comment by beraldoleal** [comment]
@renanrodrigo do you know how to do this ?

**Comment by renanrodrigo** [comment]
Discussing now with @cemsbr and @macartur .

**Comment by macartur** [comment]
This was fixed by #322
