### ISSUE TITLE
MultipartRequest creation

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#308]
Although MultipartReplies are created by the switch and need only to be unpacked correctly (see #307), the process of creating multipart requests, say PortStatsRequest, involves:
1. Create a PortStatsRequest object.
2. Create a MultipartRequest object.
3. Define the correct type of the Multipart Request.
4. Assign the PortStatsRequest object as the MultipartRequest body.
5. Pack.

As each multipart request has an unique type related to an unique body, shouldn't the library be able to create the MultipartRequest object based only in the specific request we need? If so, the process should be:
1. Create a PortStatsRequest object.
2. Pack.

And then we'd had a full MultipartRequest with the correct type and body, rendering it much easier to handle this in NApps creation.

**Comment by cemsbr** [comment]
As we've discussed, we need a blueprint.

**Comment by beraldoleal** [comment]
@renanrodrigo we decided to store all blueprints and discussion about blueprints, on kytos repo. even if is a specific project. Can you move there, please ? Please, also add the subject as other blueprints.

**Comment by renanrodrigo** [comment]
@beraldoleal Done.

**Comment by beraldoleal** [comment]
@renanrodrigo thanks.

**Comment by beraldoleal** [comment]
@renanrodrigo where is the issue on kytos ? Can you link here, please ?

**Comment by renanrodrigo** [comment]
https://github.com/kytos/kytos/issues/311

I did not copy all of the text from this issue because a better explanation is given in the blueprint.

**Comment by beraldoleal** [comment]
@renanrodrigo sure, we should have on issue only a short description. Thanks.

I'm closing this in order to discuss there.
