### ISSUE TITLE
setup.py assert python3.6 and setuptools

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#328]
assert python3.6 and setuptools installed at beggining of setup.py

**Comment by erickvermot** [comment]
should I open similar issues on the other projects?
kytos-napps also depends on pip.

I believe setup.py could state so in a clear human readable format if some of theese requirements is not satisfied.

**Comment by diraol** [comment]
@erickvermot pip should not be a requirement, therefore @macartur is doing a cleanup to remove its necessity. =)

**Comment by beraldoleal** [comment]
@diraol the problem is that in some distros you dont have pip or setuptools by default. (I think that is  @erickvermot case). But yes for pip, I accepted few pull requests about removing pip from setup.py. So this should fix at least pip problem.

**Comment by beraldoleal** [comment]
setup.py is not using pip anymore. I will close this and if the problem persists please reopen.
