### ISSUE TITLE
Check dependency: python3-pycodestyle

### ISSUE THREAD

**Issue by beraldoleal** [kytos/python-openflow#331]
python3-pycodestyle should not be necessary to install python-openflow.

@phls do you have more details ?

**Comment by cemsbr** [comment]
@beraldoleal, I didn't get it. There are no dependencies for python-openflow. "requirements.txt" has no packages, only comments.

**Comment by macartur** [comment]
This package is needed to install pylama.

**Comment by diraol** [comment]
I Think we have a misunderstanding here. As far as I remember this issue was supposed to be from `kytos-utils` instead of `python-openflow`.
(but pylama still not a requirement for this project, it is just a dev-requirement).

@beraldoleal and @phls can you confirm this for us, please?

**Comment by beraldoleal** [comment]
Yes, was a misunderstanding, we already fixed this with @phls.
