### ISSUE TITLE
Version unpacking problems

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#344]
Wrong unpack version.
Should lead to exception.
::

    >>> from pyof.v0x01.common.utils import unpack_message
    >>> m = unpack_message(b'\x04\x00\x00\x08\x00\x00\x00\x01') # v0x04 Hello message
    >>> m.header.version
    UBInt8(1)

**Comment by renanrodrigo** [comment]
It happens because unpack_message creates the header before unpacking the data to it, and the version is defined in creation.
I think the best way to solve this problem is not a local correction, but refactoring the code to put unpack_message in `/foundation/` and changing it's behavior: unpack the whole data (including the protocol version).

**Comment by diraol** [comment]
Proposal:

Create a "general" `unpack` method under `foundation/utils` and a specific `unpack` under `<version>/utils`, for each version. The "general" unpack would discover the correct version to be used and then call the specific unpack.

May be the specific unpack methods should raise some exception, but I think that this (validation/exception) may be related to the issue #96 anyway.

**Comment by erickvermot** [comment]
I agree. But I also think 'version handling' could be implemented in some other way.
The problem with "disovering" the correct version is that a connection that was setup for working with v0x01 or some other version, should reject packets from other versions.
[blueprint EP09](https://github.com/kytos/kytos/blob/master/docs/blueprints/EP009.rst) talks about this, and in *Proposal/Other comments* section proposes a way to deal with versions.

**Comment by erickvermot** [comment]
this will be solved if issue https://github.com/kytos/python-openflow/issues/407 is solved.
