### ISSUE TITLE
common.action.ActionSetField() compliance

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#348]
Refers to #164 [v0x04] Helps on OF spec understanding.

@diraol asked about the struct ``ofp_action_field`` struct, currently implemented as ``v0x04.common.action.ActionSetField()`` .
I checked the specs (OF1.3.0), and the implemented code, and I believe the
implementation does not complies with the spec.
It also affects:
``v0x04.common.flow_match.Match()`` and
``v0x04.common.flow_match.OxmHeader()`` (not implemented I believe)

In the current implementaion, OXM_TLV is treated as 4 independent 8bits 'field' in ``Match`` and in ``ActionSetField``.

On #164, @diraol wrote:
> It seems to be a UBInt8 array of size 4, and its content may be a "OXM TLV". But there it is not clear what is a OXM TLV. There is no structs on the spec for that, despite table 9 on page 41.
> So, this struct has a variable length?

As I understand, OXM TLV is a simple TLV (Type Length Value), and therefore it has variable length. Its minimum length is 4 Bytes (figure 4 of pg 39):
- 1 UBInt16 for oxm_class (one of 
- 7bits for oxm_field (and 1bit for oxm_hasmask - not used in this case) 
- 1 UBInt8 for Length.

\+ the value field
- 1 (length - 3bytes) oxm_value

the union of ``oxm_class`` and ``oxm_field`` (23 bits: ``OXM_TLV[:3] >> 1``) is called ``oxm_type``. Possible ``oxm_class`` and ``oxm_field`` are in pg 40 and 42  respectively.

From the spec:
> The field contains a header field described using a single OXM TLV structure (see A.2.3). Set-Field
actions are defined by oxm_type, the type of the OXM TLV, and modify the corresponding header field in the packet with the value of oxm_value, the payload of the OXM TLV.

I hope I could clear the subject a bit. And I can implement it if needed.

**Comment by erickvermot** [comment]
TODO: check 1.3.5

**Comment by erickvermot** [comment]
@cemsbr and @diraol reimplemented another solution to this issue as another branch,
they will make another PR, and decided to close
https://github.com/kytos/python-openflow/pull/392
and
https://github.com/kytos/python-openflow/pull/405

I was asked to move the first commit of https://github.com/kytos/python-openflow/pull/392 to another PR so they can start reviewing it. I'll make a reference to the other PR here once it is open.

**Comment by erickvermot** [comment]
@cemsbr @diraol,
I took a look at your PR, and many things are not working as expected.
I will paste here some small tests that don't work with you implementation.

```
>>> o1 = OxmTLV(OxmClass.OFPXMC_OPENFLOW_BASIC,
    	        oxm_field=OxmOfbMatchField.OFPXMT_OFB_IN_PHY_PORT,
    			oxm_hasmask=False,
    			oxm_value=b'abcde')

>>> o2 = OxmTLV(OxmClass.OFPXMC_OPENFLOW_BASIC,
    			oxm_field=10,
    			oxm_hasmask=False,
    			oxm_value=b'abcdef')

>>> o3 = OxmTLV(OxmClass.OFPXMC_OPENFLOW_BASIC,
    			oxm_field=64,
    			oxm_hasmask=False,
    			oxm_value=b'')

>>> o = OxmTLV()

>>> m = Match(match_type=MatchType.OFPMT_OXM, oxm_match_fields=[o1, o2])

################
# Testing Match:

>>> mu = Match()

>>> mu.unpack(m.pack())

>>> mu.oxm_match_fields
[<pyof.v0x04.common.flow_match.OxmTLV at 0x7f1e0179ccf8>]  # This is wrong



################
# Testing OxmTLV

>>> o1.pack()
b'\x80\x00\x02\x05abcde'

>>> o2.pack()
b'\x80\x00\x14\x06abcdef'

>>> o3.pack()
b'\x80\x00\x00\x00'			# This is wrong

>>> o.unpack(o1.pack())

>>> o.oxm_class, o.oxm_field, o.oxm_value
(UBInt16(32768), 4, BinaryData(b'abcde'))			# This is wrong + values are not parssed

>>> o.unpack(o2.pack())

>>> o.oxm_class, o.oxm_field, o.oxm_value
(UBInt16(32768), 40, BinaryData(b'abcdef'))			# This is wrong

>>> o.unpack(o3.pack())

>>> o.oxm_class, o.oxm_field, o.oxm_value
(UBInt16(32768), 0, BinaryData(b''))				# This is wrong (beacause of the pack)



################
# Testing ListOfOxmHeader

>>> l  = ListOfOxmHeader([o, o1, o2, o3])

>>> lu = ListOfOxmHeader()

>>> lu.unpack(l.pack())

>>> lu
[<pyof.v0x04.common.flow_match.OxmTLV at 0x7f1e017540f0>]  # This is wrong

```

**Comment by erickvermot** [comment]
After @cemsbr made some changes, some of these bugs are fixed, but not all of them. o3 pack/unpack is still not working correctly.
```
>>> o.unpack(o3.pack())
>>> o.oxm_class, o.oxm_field, o.oxm_value
(UBInt16(32768), 0, b'')
```

ActionSetField fix is still missing in the PR.

\+ I still do not see why this PR (which augment the code in 212 new lines) is prefered over https://github.com/kytos/python-openflow/pull/392 which introduces only 92 new lines (or #405 with 162 lines). Since many of the commits from 392 were presented now as new PRs as was requested, I still think just rebasing 392 once these are accepted is a better solution. But that's just my opinion.

**Comment by cemsbr** [comment]
That's because 64 is an invalid oxm_field value that causes overflow. The commit above validates the enum value.

**Comment by erickvermot** [comment]
64 is not necessarily an invalid ``oxm_field``.
And the validations the commit realizes are incorrect, as they do not consider the class. see review.

**Comment by cemsbr** [comment]
The fact that it doesn't cover all the cases does not mean it is incorrect, but incomplete. The complete validation is not trivial and we can open an issue for that.

**Comment by cemsbr** [comment]
As `ActionSetField` doesn't seem to be directly related to OXM unpacking bug, I'm creating #428 and lowering the priority of this issue.

**Comment by erickvermot** [comment]
@cemsbr 
This issue is about OxmTLV implementation, which is used by Match and ActionSetField. (please take a look at the first comment).
There is even a working solution on PR https://github.com/kytos/python-openflow/pull/392 and https://github.com/kytos/python-openflow/pull/405, which you guys refuse to review.
You chose to create a new branch and copy parts of it, and until now it doesn't work as expected, but that is your call, you may do as you like. But I see no reason to create a new issue for the same problem.

about the validation, in this case it is actually incorrect as the class is not being taken into acount.
