### ISSUE TITLE
Update python-openflow in PyPi

### ISSUE THREAD

**Issue by macartur** [kytos/python-openflow#359]
The python-openflow package is broken. We can update the python-openflow package using the commits until the commit  https://github.com/kytos/python-openflow/commit/1b5682b0f5edeb5bcb90a70f4c2ee14fe3eb4e02 .

**Comment by cemsbr** [comment]
Please, @beraldoleal, also upload the wheel as a result of `python setup.py bdist_wheel`.

**Comment by cemsbr** [comment]
dev1 is in PyPI.
