### ISSUE TITLE
Headers are being created as class attributes instead of instance attributes

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#361]
Messages are being created with its header as a class attribute instead of a instance attribute. This makes all the instances have the same header, and consequently the same XID.

**Comment by diraol** [comment]
This may be fixed by the changes that need to be done to solve the issues: #157, #198 and #237 
This is a behavior that we have already identified while proposing the solution for #157 and it is meant to be fixed by the refactor that solves this issue.

**Comment by erickvermot** [comment]
https://github.com/kytos/python-openflow/compare/master...erickvermot:new_generic_message
fixes this in a simple way.
This also fixes the XID problem still present (despite https://github.com/kytos/python-openflow/issues/224).

If the 'work_or_pass' logic is accepted (https://github.com/kytos/python-openflow/pull/392/commits/a4c1f0535d9e1a796c85785e525278a0e4490943), it MessageStruct can become even simpler:
https://github.com/kytos/python-openflow/compare/master...erickvermot:new_generic_message_work_or_pass
