### ISSUE TITLE
Release with Cleanner fixed.

### ISSUE THREAD

**Issue by phls** [kytos/python-openflow#375]
Please release a new version without docs because 2017.1b2 has the old class Cleanner.

**Comment by beraldoleal** [comment]
@phls we are going to release b3 this week. Do you need b2 ? or can wait until b3 ?

**Comment by phls** [comment]
Sure, no problem. I wait.

**Comment by beraldoleal** [comment]
@diraol @cemsbr ?

**Comment by diraol** [comment]
As far as I remember this is already fixed, right @phls ?

**Comment by phls** [comment]
Yes, it's ok now.
