### ISSUE TITLE
v0x04 Hello unpack bug

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#378]
https://github.com/kytos/python-openflow/issues/303 was opened so that hello messages could accept optional elements like the versionbitmap.
Unfortunately the proposed code is unable to unpack the messages. (see bellow).

A few comments about it:
- The ListOfHelloElements is declared as a FixedTypeList, but in the docstring of the FixedTypeList unpack method is is stated that it considers all the elements to be of the same size, which is not true for the list of hello elements.
- The way it is constructed, a HelloElementHeader with a unknown ElementType will not be accepted for the ElementType will not be listed in the HelloElementType Enum.

```python
In [7]: p = b'\x04\x00\x00\x10\x00\x00\x00\x01\x00\x01\x00\x08\x00\x00\x00\x12'

In [8]: from pyof.v0x04.common.header import Header
In [9]: h = Header()
In [10]: h.unpack(p[:8])

In [11]: from pyof.v0x04.common.utils import new_message_from_header
In [12]: nm = new_message_from_header(h)
In [13]: nm.unpack(p[8:])

ValueError: 0 is not a valid HelloElemType

**Comment by diraol** [comment]
See https://github.com/kytos/python-openflow/issues/379#issuecomment-309828636
