### ISSUE TITLE
Provide a version independent unpack method

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#381]
pyof should provide a version independent unpack method, capable of returning an instance of the correct message class depending on its version.

A method like this is already implemented in ``kytos/napps/of_core/utils.py`` (https://github.com/kytos/kytos-napps/blob/master/napps/kytos/of_core/utils.py), and needs only to be moved to the pyof lib. (but it cannot yet deal with the cases mentioned bellow, reason why a generic hello class has been implemented):
```python
def unpack(packet):
    """Unpacks the OpenFlow packet and returns a message."""
    version = _unpack_int(packet[0])
    try:
        pyof_lib = pyof_version_libs[version]
    except KeyError:
        raise UnpackException('Version not supported')

    try:
        header = pyof_lib.common.header.Header()
        header.unpack(packet[:8])
        message = pyof_lib.common.utils.new_message_from_header(header)
        binary_data = packet[8:]
        if binary_data:
            message.unpack(binary_data)
        return message
    except (UnpackException, ValueError) as e:
        log.info('Could not unpack message: %s', packet)
        raise UnpackException(e)
```

Furthermore, a few message types should be able to be unpacked in a "version agnostic way", so that even messages with versions not yet implemented can be (at least partially) understood, and the handshake can be accomplished or its failure understood/notified.
This is the case of:
+ Hello Messages
+ Error Messages (Hello Failed for ex)
+ Echo Messages

**Comment by diraol** [comment]
Related to: kytos/python-openflow#119
