### ISSUE TITLE
Pin the requirements versions for `2017.1`

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#383]
In order to avoid future problems with packages updates that breaks compatibility or that introduce unexpected errors/behaviors, we must ping all of our requirements versions for each release. Including the requirements of the requirements.

So, for our `2017.1` release we must pin the requirements.

**Comment by cemsbr** [comment]
I notice projects pin requirement files, so devs can make a deterministic build. They also include non-versioned deps in `install_requires` (unless an issue is found with a particular dep version). I believe that pinning `install_requires` can cause us trouble regarding distribution packages (i.e. old debian-stable Python packages).

**Comment by diraol** [comment]
So, If I got it right and bringing what I saw on other projects too, we should add all requirements (and requirements of requirements) to `requirements-*.txt` and then pin each one of them. Then we should add just our main requirements on the `install_requires` without specific versions (unless needed for some specific reason). Is that right @cemsbr ?

**Comment by cemsbr** [comment]
I use a project to help in this process: https://github.com/jazzband/pip-tools

**Comment by cemsbr** [comment]
To sum up:
- Anybody can have the same build by installing the versions specified in requirements/*.txt
- To have a .deb, we won't use the recommended virtualenv forcing the current major versions. We will only use versions in setup.py when there are known problems.

Links about dependency version management:
- https://packaging.python.org/discussions/install-requires-vs-requirements/
- https://hynek.me/articles/python-deployment-anti-patterns/
- http://nvie.com/posts/pin-your-packages/
