### ISSUE TITLE
Upgrade linters

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#384]
Pylama can't keep up with linters such as pycodestyle (former PEP8). @diraol sent them a PR that had already been approved but has not been merged for months. Consequently, our code has issues that are not being reported by pylama. We should either call each linter independently and deal with their versions and different outputs, or chose another tools such as [yala](https://github.com/cemsbr/yala). I have already solved several bugs using yala.

Disclaimer: I'm yala's author.

**Comment by renanrodrigo** [comment]
@cemsbr doesn't dd0164ba0fe31351551d9ff353a9fcdaf07aab27 close this issue?

**Comment by diraol** [comment]
Fair enought @renanrodrigo.

@macartur, please try remembering to set the relationships between your PRs and the issues, specially when your PR closes an issue (like this one).
