### ISSUE TITLE
fix GenericType operators

### ISSUE THREAD

**Issue by erickvermot** [kytos/python-openflow#423]
In current implementation, ``GenericType`` does not inherit from any other class, and for that reason has to implement its own operators methods, like ``__add__`` etc...
The problem is that this leads to possible mistakes (like in the current definition of ``__lt__`` - see bellow), and also forbid ``GenericType`` s from being used with operators that are not included in the definition (like with ``__int__``, or ``__mod__``).
A much simpler solution is to make it inherit from python primitive types, as proposed here: https://github.com/kytos/python-openflow/issues/198#issuecomment-316769379 .

current problems:
```
>>> a = GenericType(2)
>>> a > a
True

>>> int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'GenericType'

>>> a // 2
TypeError: unsupported operand type(s) for //: 'GenericType' and 'int'
```

**Comment by cemsbr** [comment]
The first is fixed:

```python
>>> from pyof.foundation.base import GenericType
>>> a = GenericType(2)
>>> a > a
False
```

``int(a)`` and ``a // 2`` don't make sense for children like ``DPID``, for example.
