### ISSUE TITLE
Check dump file content

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#432]
There's a dump file for ``tests/v0x01/test_asynchronous/test_port_status.py``, but we don't know its content to create the correspondent object. If we want to use that file, we need to be sure about the parameters somehow (e.g. reading byte by byte while checking the spec).

**Comment by renanrodrigo** [comment]
I've dissected and interpreted the binary data, and IMHO it is a **valid** dump, although the switch implementation does not provide all information.

| # Bytes | Description | Situation |
|---|---|---|
| 1-8 | OpenFlow Header | Correct `type` and `length`, `xid` is set to zero. |
| 9 | Reason | Port was modified. |
| 10-16| Pad | Ok. |
| 17 - 64 | Physical Port struct | As follows: |
| 17 - 18 | Port Number | Set to 1. |
| 19 - 24 | Physical Address | MAC address: 9a:da:11:8a:f4:0c. |
| 25 - 40 | Port name | Set to 's1-eth1', null terminated as expected. |
| 41 - 44 | Port Configuration | Set to all zeros: STP, forwarding, flooding, etc. are enabled. |
| 45 - 48 | Port STP State | Set to all zeros: enabled, not learning or relaying frames. |
| 49 - 52 | Current features | Set to Copper Ethernet, 10GBps, Full duplex. |
| 53 - 56 | Advertised features | Set to all zeros: unsupported or unavailable. |
| 57 - 60 | Supported features | Set to all zeros: unsupported or unavailable. |
| 61 - 64 | Features advertised by peer | Set to all zeros: unsupported or unavailable. |

**Comment by diraol** [comment]
@renanrodrigo so, if I understood correctly, we can safely implement the test with this dumpfile to check our library, and this will be in accordance with the spec, right?

**Comment by renanrodrigo** [comment]
@diraol @cemsbr yes, sure. Just set up the class with the described values.
