### ISSUE TITLE
Add missing struct minimum-size test

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#434]
Change ``test_struct.py`` so it never skips the minimum-size test and implement the missing ones (it seems to be only one). The minimum size must be taken from the OF spec, right below the correspondent struct definition code.

**Comment by hdiogenes** [comment]
The original suggestion on #435 was this one:

> Since we should always check the 'minimun_size' against the spec information, should we require the 'minimum_size' to be always set on the child classes?
> As there is not 'abstractattribute' under the python 'ABC' class, we can:
> 
> Define 'minimun_size' as a property at use 'abstractmethod' over it's getter/setter.
> Use the init_subclass to check if the 'minimun_size' was set on the subclass (as class attribute). If not, we may raise an error for that class.
> If we do like this, we do not need the 'try/except' and the "skip" on the "test_minimum_size" method.

**Comment by hdiogenes** [comment]
Fixed in #604
