### ISSUE TITLE
[v0x04] Add defaults for classes

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#451]
Most `v0x04` classes are initiates with all their attributes set to `None`. This adds complexity and may lead to problems for the lib user.
We need to set the proper defaults for those classes based in the spec, being sensible when the document does not specify anything.

**Comment by diraol** [comment]
I totally agree with this! Default valid values are very important!

**Comment by renanrodrigo** [comment]
For Multipart Requests, I'm setting the defaults on the bodies and leaving the main request to be filled by the user before packing. Implementing kytos/kytos#311 could ease the handle of Multipart messages, but it must be discussed in the future.

**Comment by renanrodrigo** [comment]
As discussed before, most used classes are being reviewed. Some less common will be updated later.
