### ISSUE TITLE
Refactor Instruction class to improve unpacking

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#474]
Instruction class is not being unpacked correctly in some cases (like in FlowStats packets).

**Comment by renanrodrigo** [comment]
This was proven unecessary after some unpacks.

**Comment by diraol** [comment]
How so @renanrodrigo ? Why unnecessary?

**Comment by diraol** [comment]
Oh, and if the issue still closed, remove the label 'in-progress', please ;)

**Comment by renanrodrigo** [comment]
@diraol the problem was the list unpacking, being closed by #476 ...
It sure needs better implementation, but it works with this correction.
