### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by phls** [kytos/python-openflow#483]
Please verify these problems:

  File "/usr/lib/python3/dist-packages/pyof/foundation/basic_types.py", line 459
    raise ValueError(f"BinaryData can't be {type(value)} = '{value}'")
                                                                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/pyof/v0x01/controller2switch/packet_out.py", line 131
    raise ValidationError(f'{self.in_port} is not a valid input port.')
                                                                     ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/pyof/v0x04/common/flow_match.py", line 356
    raise PackException(f'Match can\'t unpack "{value}".')
                                                        ^
SyntaxError: invalid syntax

**Comment by diraol** [comment]
@phls which python version are you using?
`f'Match can't unpack "{value}".'` syntax was introduced in python3.6, so it won't work on python versions prior to 3.6.

**Comment by phls** [comment]
Hi @diraol, yes. 

$ python3 -V
Python 3.6.3rc1

**Comment by cemsbr** [comment]
Much probably the Python running the code is < 3.6. We need steps to reproduce.

**Comment by phls** [comment]
I waited few days and after a dist-upgrade the package was installed without problems.
Probably some new feature in python solved the bug.
