### ISSUE TITLE
Body of Experimenter action is not defined, leading to unpack errors

### ISSUE THREAD

**Issue by ajoaoff** [kytos/python-openflow#560]
When receiving a `FlowStats` containing an Experimenter action the unpack fails because the body is not defined, so the body is treated as if it is another action. Relates to kytos/kytos#933.

**Comment by beraldoleal** [comment]
@ajoaoff it is a body from an experimenter message defined on spec? I don't remember right, but looks like this makes sense if is defined by the vendor, right ? So python-openflow will only put the body as a "raw" data value.

Makes sense to you ?
