### ISSUE TITLE
Fix Bucket ListOfActions attribute

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/python-openflow#574]
When I create a ListOfBuckets with more than one Bucket, the first one recognizes the next buckets as actions.

**Comment by gleybersonandrade** [comment]
### Code to reproduce this error: ###

from pyof.v0x04.common.action import (
    ActionExperimenter, ActionSetField, ListOfActions)
from pyof.v0x04.common.flow_match import OxmClass, OxmOfbMatchField, OxmTLV
from pyof.v0x04.common.port import PortNo
from pyof.v0x04.controller2switch.common import Bucket, MultipartType
from pyof.v0x04.controller2switch.group_mod import GroupType, ListOfBuckets
from pyof.v0x04.controller2switch.multipart_reply import (
    GroupDescStats, MultipartReply)
​
oxmtlv1 = OxmTLV(oxm_class=OxmClass.OFPXMC_OPENFLOW_BASIC,
                 oxm_field=OxmOfbMatchField.OFPXMT_OFB_METADATA,
                 oxm_hasmask=False,
                 oxm_value=b'\x00\x00\x00\x00\x00\x00\x00\x01')
oxmtlv2 = OxmTLV(oxm_class=OxmClass.OFPXMC_OPENFLOW_BASIC,
                 oxm_field=OxmOfbMatchField.OFPXMT_OFB_METADATA,
                 oxm_hasmask=False,
                 oxm_value=b'\x00\x00\x00\x00\x00\x00\x00\x02')
​
action1 = ActionSetField(field=oxmtlv1)
action2 = ActionSetField(field=oxmtlv2)
action3 = ActionExperimenter(length=16, experimenter=0x00002320,
                             body=b'\x00\x0e\xff\xf8\x28\x00\x00\x00')
action4 = ActionExperimenter(length=16, experimenter=0x00001223,
                             body=b'\x00\x0e\xff\xff\x28\x00\x00\x00')
​
bucket1 = Bucket(length=48, weight=1, watch_port=PortNo.OFPP_ANY,
                    watch_group=PortNo.OFPP_ANY,
                    actions=ListOfActions([action1, action2]))
bucket2 = Bucket(length=48, weight=1, watch_port=PortNo.OFPP_ANY,
                    watch_group=PortNo.OFPP_ANY,
                    actions=ListOfActions([action3, action4]))
​
buckets = ListOfBuckets([bucket1, bucket2])
buff = buckets.pack()
obj = ListOfBuckets()
obj.unpack(buff)

**Comment by ajoaoff** [comment]
The error happens because `Bucket` `unpack` uses `GenericStruct` `unpack`, but it does not work when the size of the elements is not fixed, like a list. As it does not know the size of the list, it tries to unpack the whole remaining buffer into the list.
