### ISSUE TITLE
Create unit tests for OpenFlow 1.3 messages

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/python-openflow#581]
We have to create some tests for OpenFlow 1.3 messages.

**Comment by gleybersonandrade** [comment]
Related: #564, #577

**Comment by hdiogenes** [comment]
Went from something about 50% to 97.97%

**Comment by hdiogenes** [comment]
OpenFlow 1.0 is 97.97% covered, 1.3 should be closer to that - it's [currently at 76%](https://codecov.io/gh/kytos/python-openflow/tree/master/pyof).

**Comment by hdiogenes** [comment]
The original 1.3 coverage was around 50% and with this issue it has been improved to 76%. We can create another issue with the task of bringing it over 90%.
