### ISSUE TITLE
Check enums and enums BitMask with OpenFlow spec

### ISSUE THREAD

**Issue by beraldoleal** [kytos/python-openflow#62]
All enums and enums with BitMask field needs to be a argument (enum_ref) on respective attribute.

**Comment by cemsbr** [comment]
Could you provide an example, please?

**Comment by diraol** [comment]
Take a look at the config attribute from port_mod message.
On our class definition we should add the ref to specified enumeration or
bitmask

Diego Rabatone Oliveira
Em 7 de jun de 2016 5:55 PM, "Carlos Eduardo Moreira dos Santos" <
notifications@github.com> escreveu:
