### ISSUE TITLE
Incomplete parsing of add-group/mod-group messages

### ISSUE THREAD

**Issue by dgarc330** [kytos/python-openflow#633]
Hello everyone, as I was working in parsing the Openflow messages for the ofp_sniffer application, I came accross this issue:

I am working with the add-group and mod-group openflow actions. Now, according to the Openflow Specification, the add-group and mod-group actions contain the following attributes: command, type, pad, group_id, and bucket[ len, weight, watch_port, watch_group, pad, action_header[] ].

When I execute the commands to apply those actions this is the output: 
**- First to create a group:**
` ovs-ofctl add-group tcp:127.0.0.1:6654  group_id=8,type=indirect,bucket=mod_dl_src=00:00:00:11:11:6654,mod_dl_dst=00:00:00:22:22:6654,output:1 -OOpenFlow13`

- This is the output I get from the sniffer:
  **- Packet #23** - 2021-04-22 13:49:18.002970 127.0.0.1:40396 -> 127.0.0.1:6654 Size: 146 Bytes
  OpenFlow Version: 1.3(4) Type: OFPT_GROUP_MOD(15) Length: 80  XID: 4
  GroupMod Command: OFPGC_ADD(0) Type: OFPGT_ALL(0) Pad: 0 Group_id: 8
  **Bucket[lenght]: None Bucket[weight]: None Bucket[watch_port]: None Bucket[watch_group]: None
  Bucket[actions]: None**

**-Then to modify said group:**
`ovs-ofctl mod-group  tcp:127.0.0.1:6654  group_id=8,type=indirect,bucket=mod_dl_src=00:00:00:12:12:6654,mod_dl_dst=00:00:00:22:22:6654,output:1 -OOpenFlow13`
- This is the output I get from the sniffer:
**- Packet #21** - 2021-04-22 13:59:10.405240 127.0.0.1:40428 -> 127.0.0.1:6654 Size: 146 Bytes
OpenFlow Version: 1.3(4) Type: OFPT_GROUP_MOD(15) Length: 80  XID: 4
GroupMod Command: OFPGC_MODIFY(1) Type: OFPGT_SELECT(1) Pad: 0 Group_id: 8
**Bucket[lenght]: None Bucket[weight]: None Bucket[watch_port]: None Bucket[watch_group]: None
Bucket[actions]: None**

As you can see, most of the attributes are not detected even though the packet byte size is 80 which suggests that its containing more data than what it is been shown. To try and troubleshoot this I did a tcpdump to see the traffic that was going on and here is the result:
![image](https://user-images.githubusercontent.com/43040493/115748112-de346e80-a363-11eb-8425-62f3d1cde715.png)

Jeronimo then analyzed it further with wireshark, and he found that as suspected, the packet has more data than what was been shown:
![image](https://user-images.githubusercontent.com/43040493/115747233-08d1f780-a363-11eb-95f6-d727a8d359e7.png)

I though it might be the sniffer, but when I simply printed the message been returned by python-openflow this is what I got: 
` print(msg.buckets._pyof_class.__dict__)` 

 `{‘__module__': 'pyof.v0x04.controller2switch.common', '__doc__': 'Bucket for use in groups.', 'length': UBInt16(None), 'weight': UBInt16(None), 'watch_port': UBInt32(None), 'watch_group': UBInt32(None), 'pad': Pad(4), 'actions': [], '__init__': <function Bucket.__init__ at 0x7fb6c97faea0>, 'unpack': <function Bucket.unpack at 0x7fb6c97faf28>, 'get_size': <function Bucket.get_size at 0x7fb6c9809048>}`

Also notes how the actions[] appears to be empty, but the output from wireshark proves that it should contain at least 3 actions.

After seeing this, is that we suspected that maybe there is an issue with the python-openflow and the parsing of messages. If you could try to test this out on your end and share your results it would be great to see what is going on.

**Comment by ajoaoff** [comment]
Hi, @dgarc330. @hdiogenes and I have debugged this issue, and found that the problem is in `ofp_sniffer`. It is dealing with `buckets` as if it was only one element, but it is a list. The OpenFlow specification states that add-group and mod-group have a list of buckets, not a bucket. 
Printing the message from python-openflow:
```
print(gm.buckets[0].__dict__)
{'length': UBInt16(64), 'weight': UBInt16(0), 'watch_port': UBInt32(4294967295), 'watch_group': UBInt32(4294967295), 'pad': Pad(4), 'actions': [<pyof.v0x04.common.action.ActionSetField object at 0x7fb87531f9b0>, <pyof.v0x04.common.action.ActionSetField object at 0x7fb86c062fd0>, <pyof.v0x04.common.action.ActionOutput object at 0x7fb86c062cf8>]}
```

**Comment by dgarc330** [comment]
@ajoaoff , in our side even when we don't use the sniffer and just print the openflow message, this is what we get:
`print(msg.buckets._pyof_class.__dict__)
{'__module__': 'pyof.v0x04.controller2switch.common', '__doc__': 'Bucket for use in groups.', 'length': UBInt16(None), 'weight': UBInt16(None), 'watch_port': UBInt32(None), 'watch_group': UBInt32(None), 'pad': Pad(4), 'actions': [], '__init__': <function Bucket.__init__ at 0x7f858fa0bae8>, 'unpack': <function Bucket.unpack at 0x7f858fa0bb70>, 'get_size': <function Bucket.get_size at 0x7f858fa0bbf8>}`

Could you please share the commands and procedures you used to debug the issue?

**Comment by ajoaoff** [comment]
`buckets` is a list of a fixed type, so what you are printing is the information about the class of the elements of that list, not the elements themselves. If you look at the message I printed in my previous comment, I printed `buckets[0].__dict__`, not `buckets._pyof_class.__dict__`.
The correct approach is to iterate of `buckets`. 
```
for bucket in msg.buckets:
     print(bucket.__dict__)
```
