### ISSUE TITLE
Write a CLA

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#76]

**Comment by cemsbr** [comment]
Suggestion: do like [Canonical](http://www.ubuntu.com/legal/contributors/submit) and generate a CLA using [project harmony](http://selector.harmonyagreements.org/). There's also the [Apache CLA](https://www.apache.org/licenses/icla.txt).

**Comment by beraldoleal** [comment]
Done. Everyone should agree with this CLA:

http://kytos.io/cla/
