### ISSUE TITLE
Fill doc gaps

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#77]
- [x] How to create upstream remote in CONTRIBUTE.md
- [x] make doctest together with other tests (everywhere)

Suggestion: create a Makefile in root folder to run both unit tests and doctests with "make tests".

**Comment by beraldoleal** [comment]
Are you sure that there is no way to do this using `setup.py` and avoid the `Makefile` ?

**Comment by diraol** [comment]
Doctest on setup.py done on f5b3384e48355af505329546a241ce85c0400440 ! ;)
