### ISSUE TITLE
Consider the use of pylint to improve the code

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#78]
We have same warnings like unreachable code, different number of arguments in overridden method, and some errors, among false positives, that are worth fixing/checking.

**Comment by diraol** [comment]
Can you provide some samples and/or where these warnings happens?

Diego Rabatone Oliveira
Em 8 de jun de 2016 7:39 PM, "Carlos Eduardo Moreira dos Santos" <
notifications@github.com> escreveu:

**Comment by cemsbr** [comment]
This is easy to check. In root folder, run `pylint pyof`. There are plenty of them.

**Comment by beraldoleal** [comment]
Definitely pylint is a good tool and should try it. But we need to be careful. We dont need to check everything that pylint suggests. I think that we could start discussing one by one that `pylint -E` (only errors) reports.

**Comment by diraol** [comment]
Just one thing: Remember to run pylint with/from python3 for correct checks.

**Comment by cemsbr** [comment]
Just a note: we can ignore some errors using pylintrc file and also special comments in source for specific cases.

**Comment by diraol** [comment]
Using pylintrc seems better to me.
​

**Comment by beraldoleal** [comment]
I would prefer to avoid have a `.pylintrc`. We can add the proper command line on `docs/Makefile` to ignore few items and call `pylint` and any syntax checker, like `pep8` utility..

**Comment by beraldoleal** [comment]
We should include pylint on tests and document the all tests on CONTRIBUTE section.
