### ISSUE TITLE
[v0x01] Implement Packing and Unpacking tests

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#8]
- **Asynchronous** messages:
  - [ ] error_msg.py
  - [ ] flow_removed.py
  - [ ] packet_in.py
  - [ ] port_status.py
- **Common** messages:
  - [ ] action.py
  - [ ] flow_match.py
  - [ ] header.py
  - [ ] phy_port.py
  - [ ] queue.py
- **Controller2Switch** Messages
  - [ ] aggregate_stats_reply.py
  - [ ] aggregate_stats_request.py
  - [x] barrier_reply.py
  - [x] barrier_request.py
  - [ ] common.py
  - [ ] desc_stats.py
  - [x] features_reply.py
  - [x] features_request.py
  - [x] flow_mod.py - flow_delete
  - [ ] flow_mod.py - flow_add
  - [ ] flow_stats.py
  - [ ] flow_stats_request.py
  - [ ] get_config_reply.py
  - [ ] get_config_request.py
  - [ ] packet_out.py
  - [ ] port_mod.py
  - [ ] port_stats.py
  - [ ] port_stats_request.py
  - [ ] queue_get_config_reply.py
  - [ ] queue_get_config_request.py
  - [ ] queue_stats.py
  - [ ] queue_stats_request.py
  - [x] set_config.py
  - [ ] stats_reply.py
  - [ ] stats_request.py
  - [ ] table_stats.py
- **Foundation**
  - [ ]  base.py
  - [ ]  basic_types.py
- **Symmetric** messages
  - [x] echo_reply.py
  - [x] echo_request.py
  - [x] hello.py
  - [ ] vendor_header.py

**Comment by cemsbr** [comment]
By implementing these tests, we have fixed several bugs (PR #133). Tests for the dump files whose content we don't know are currently being skipped. We need more dump files.

**Comment by diraol** [comment]
The pack/unpack now depends only on the existence of the raw `dat` files to be tested against.
