### ISSUE TITLE
Check  1.0.1 and 1.0.2 compliance

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#80]

**Comment by cemsbr** [comment]
Some values are forbidden for the in_port attribute of PacketOut message. Currently, it seems that we allow setting these invalid values. Should we validate it or assume that the controller will generate valid messages?

**Comment by diraol** [comment]
I think that this should be validated on the lib, with the `is_valid`
method (see `GenericStruct` class for reference).

**Comment by cemsbr** [comment]
I read them and filed #96. I will override it and call super.

**Comment by cemsbr** [comment]
I have some doubts about validation. I noticed that the (unreachable) validation code either returns True or False and exceptions are only thrown later, in `pack()`. The problem with this approach is that the exception has no useful information about how to fix the invalid OF message. In this commit, I throw an exception during the validation with a message to help the user fix it. Besides, I was not sure whether to use `ValidationError` or `BadValueException`, so I threw a standard python `ValueError` exception.

**Comment by beraldoleal** [comment]
I agree with you, we should capture the proper exception. But a method named `is_valid` should always return True or False, because is a question.

Please see with @diraol the best approach to fix this and fix/re submit the PR #99.

**Comment by cemsbr** [comment]
After our discussion, I found [this post](http://stackoverflow.com/questions/6470428/catch-multiple-exceptions-in-one-line-except-block) about multiple validation errors and came up with [this code](https://gist.github.com/cemsbr/cfa00ea8382a0962a2437ab01da6d44f). What do you think?

**Comment by diraol** [comment]
I came across with [this propose](https://gist.github.com/diraol/cd965996c07a012372f8c1027be1c5a1).
