### ISSUE TITLE
List requirements

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#81]
What are the requirements for running, developing, documenting, etc? Maybe list them separately in virtualenv text files.

**Comment by beraldoleal** [comment]
For now we have .requirements.txt for development and def we should keep the documentation requirements away from this default .requirements.txt. As discussed, for now, lets just try to keep 2 .requirements files. We can return to this issue and discuss the use of virtualenvs on the future.

**Comment by diraol** [comment]
Shouldn't we have created the docs-requirements file? (with sphynx, pylint, maybe pep8, pyflakes, doctest and something like that?)

**Comment by beraldoleal** [comment]
Yes. See my coment 14 days ago.

**Comment by diraol** [comment]
(You commented and closed the issue.... so this was out of our radar of tasks to be done ;)

**Comment by beraldoleal** [comment]
Yes, sorry about that. Please, keep it open until we have this requirements-docs.txt.
