### ISSUE TITLE
Creation of new basic_type (IP_ADDR)

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#85]
Should we create a new basic_type, such as we have done with `HWAddress`, to ip address fields?

This new class could be just a "IPAddr" that supports both ipv4 and ipv6, so we don't need to implement two classes.

It would be used on `nw_src` and `nw_dst` attributes of `common.flow_match.Match` class (until now I've just reviewed up to this point on the spec, pg.20)

**Comment by beraldoleal** [comment]
Yes, def is a good idea.

**Comment by beraldoleal** [comment]
This was described also here: https://github.com/kytos/python-openflow/pull/185#issuecomment-250750896
