### ISSUE TITLE
Vendor extensions

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#87]
The `VendorHeader` class (`struct ofp_vendor_header`), located at in the symmetric module, exists to build vendor specific extensions messages.

I am in doubt if this class should accept extra attributes, not previously declared, as stated on the specification:

> /\* Vendor-defined arbitrary additional data. */

**Comment by beraldoleal** [comment]
Each vendor can implement any struct here. So we should implement like a binary data, and ignore, for now.

**Comment by beraldoleal** [comment]
@diraol  Is easy to make it a binary data, right ?

**Comment by diraol** [comment]
Yes! I think that this is the solution.
(Knowing closely how the things work make it easier to understand how to solve this problems. =) Long live to practical knowledge!)
