### ISSUE TITLE
Review body attribute

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#88]
Review `body` attribute of `...controller2switch.stats_request` and `...controller2switch.stats_reply` to evaluate if this attribute its type. It has been defined as a `ConstantTypeList`, but may be it could be a `UBInt8` (to act as a pointer) or a `BinaryData` generic_type field.

**Comment by beraldoleal** [comment]
For now, lets assume that body is instantiated by the developer. We should override pack() and unpack() on these cases.
