### ISSUE TITLE
Multiple possibles enums on one attribute

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#89]
On the `asynchronous.error_type.ErrorType` class, the `code` attribute is an element of a enum, but the enum is dependent on the value of `error_type` attribute.

For example. If `error_type` is `OFPET_HELLO_FAILED`, then `code` should be one option of `HelloFailedCode`. If `error_type` is `OFPET_BAD_REQUEST`, then `code` should be one option of `BadRequestCode` and so on.

How to deal with this behavior?

**Comment by beraldoleal** [comment]
@diraol Is this the same situation of Flow Mod Error ? If yes, we should rewrite pack() and unpack() for theses cases, right ?

**Comment by diraol** [comment]
@beraldoleal There is no "flow mod error" message (it is just an error message), and this is what @cemsbr fixed some weeks ago, as far as I remember.

**Comment by beraldoleal** [comment]
Yes, @diraol It was this error that I was referring to. So this is close, right ?

**Comment by cemsbr** [comment]
I think @diraol referred to #108. But the `code` attribute wasn't changed; it is only an `int` after unpacking, not an *Code enum.
