### ISSUE TITLE
Implement unpacking tests

### ISSUE THREAD

**Issue by diraol** [kytos/python-openflow#9]
- **Asynchronous** messages:
    - [ ] error_msg.py
    - [ ] flow_removed.py
    - [ ] packet_in.py
    - [ ] port_status.py
  - **Common** messages:
    - [ ] action.py
    - [ ] flow_match.py
    - [ ] header.py
    - [ ] phy_port.py
    - [ ] queue.py
  - **Controller2Switch** Messages
    - [ ] aggregate_stats_reply.py
    - [ ] aggregate_stats_request.py
    - [x] barrier_reply.py
    - [ ] barrier_request.py
    - [ ] common.py
    - [ ] desc_stats.py
    - [ ] features_reply.py
    - [ ] features_request.py
    - [ ] flow_mod.py
    - [ ] flow_stats.py
    - [ ] flow_stats_request.py
    - [ ] get_config_reply.py
    - [ ] get_config_request.py
    - [ ] packet_out.py
    - [ ] port_mod.py
    - [ ] port_stats.py
    - [ ] port_stats_request.py
    - [ ] queue_get_config_reply.py
    - [ ] queue_get_config_request.py
    - [ ] queue_stats.py
    - [ ] queue_stats_request.py
    - [ ] set_config.py
    - [ ] stats_reply.py
    - [ ] stats_request.py
    - [ ] table_stats.py
  - **Foundation**
    - [ ]  base.py
    - [ ]  basic_types.py
  - **Symmetric** messages
    - [ ] echo_reply.py
    - [ ] echo_request.py
    - [ ] hello.py
    - [ ] vendor_header.py

**Comment by abaruchi** [comment]
Some messages (such as `echo_request`, `echo_reply`) does not have a body. The unpack method is called for that kind of message with no data and it should return None. Anything different than that should fail the test.

**Comment by cemsbr** [comment]
Now, both packing and unpacking tests are done at once. Moved unpacking tests to issue #8 .
